spring.application.name=megabackend
server.port=8080
# App
app.jwt.secret-key=${JWT_SECRET_KEY}
app.jwt.expiration-time=3600
app.client.http.addresses=${CLIENT_ADDRESSES}
app.email.user.info.address=${EMAIL_USER_INFO_ADDRESS:}
app.email.resend.api.key=${RESEND_API_KEY:}
# Database
spring.datasource.url=jdbc:postgresql://${DATABASE_URL}/mega
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB