spring.application.name=megabackend
#
# App
#
app.jwt.secret-key=${JWT.SECRET.KEY}
app.jwt.expiration-time=${JWT.EXPIRATION.TIME}
app.client.http.addresses=${CLIENT.ADDRESSES}
#
# Database
#
spring.datasource.url=jdbc:postgresql://${DATABASE.URL}
spring.datasource.username=${DATABASE.USERNAME}
spring.datasource.password=${DATABASE.PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB