CREATE TABLE "mega_user"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255),
    CONSTRAINT uc_username UNIQUE (username)
);
