CREATE TABLE "mega_user"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    theme         VARCHAR(255),
    CONSTRAINT uc_username UNIQUE (username)
);

CREATE TABLE "note"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note       VARCHAR(255)             NOT NULL,
    color      VARCHAR(255),
    created_by BIGINT                   NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT                   NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_note_mega_user_created_by FOREIGN KEY (created_by) REFERENCES "mega_user" (id),
    CONSTRAINT fk_note_mega_user_updated_by FOREIGN KEY (updated_by) REFERENCES "mega_user" (id)
)