CREATE TABLE "email"
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject   VARCHAR(998) NOT NULL,
    message   TEXT         NOT NULL,
    send_from VARCHAR(320) NOT NULL,
    send_to   VARCHAR(320) NOT NULL,
    resend_id VARCHAR(255) UNIQUE,
    status    VARCHAR(32)  NOT NULL
);
